### ISSUE TITLE
Ctrl+C on `cargo run`

### ISSUE THREAD

**Issue by alexreg** [rust-lang/rustup.rs#806] opened 2016-11-11 15:10 UTC
When I Ctrl+C on cargo run and my Rust program is set up to intercept the signal, the Rustup process stops and returns control to the terminal, even though my Rust program (and indeed Cargo) may still be running. I've observed this on the latest version of Rustup.

I think it would be best for Rustup to do something similar to what `cargo run` does, and intercept Ctrl+C when running a program, and ignore it – instead, it should just check regularly to see if the program (`cargo`) has exited.

Note: this is confirmed not to be a `cargo` issue, as per https://github.com/rust-lang/cargo/issues/3281.

**Comment by KalitaAlexey** [comment] 2017-01-03 10:56
What is the status of the issue?

**Comment by KalitaAlexey** [comment] 2017-02-26 07:36
What is the status of the issue?
Is it still relevant?
I can work on it if it is relevant.

**Comment by alexreg** [comment] 2017-02-26 22:41
Yep, very much relevant still, I believe.

**Comment by KalitaAlexey** [comment] 2017-02-27 10:16
I am working on it.

**Comment by brson** [comment] 2017-03-17 01:43
I'd like to solve this and https://github.com/rust-lang-nursery/rustup.rs/issues/845 without giving up fork/exec. A strategy along the lines @alexreg describes in the op seems workable.

**Comment by brson** [comment] 2017-03-17 01:44
Some rationale here: https://github.com/rust-lang-nursery/rustup.rs/pull/972#issuecomment-287243676

**Comment by Vlad-Shcherbina** [comment] 2019-09-21 22:37
This still happens on Windows.

### Steps to reproduce
1. Create the following program:
    ```rust
    // [dependencies]
    // ctrlc = "*"
    fn main() {
        ctrlc::set_handler(move || {
            println!("Ctrl-C received, but I'm not exiting.");
        });
        loop {}
    }
    ```
2. `cargo run` (where cargo is rustup)
3. Press `Ctrl-C`.

### Expected result
The program should print `Ctrl-C received, but I'm not exiting.` and continue running.

### Actual result
The program terminates.

### Version info
```
> rustup --version
rustup 1.18.3 (435397f48 2019-05-22)
```

---------------

I tried it without (`C:\Users\username\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\bin\cargo.exe run`). It works as expected.

Cargo itself used to have this problem before (https://github.com/rust-lang/cargo/issues/4575), but it was solved with this workaround: https://github.com/rust-lang/cargo/pull/6004.

**Comment by kinnison** [comment] 2019-09-23 09:16
@alexcrichton Do you have any idea of the complexity of resolving this for rustup?

**Comment by alexcrichton** [comment] 2019-09-23 13:45
The Cargo solution looked like https://github.com/rust-lang/cargo/pull/6004 for Windows, so based on that I'd guess it'd have a relatively small impact?

**Comment by kinnison** [comment] 2019-09-25 07:40
Assuming #2014 builds OK, could @Vlad-Shcherbina or @alexreg please go to the PR, go through to the appveyor build, find the artifact, download a test copy of `rustup` install it and give it a go?

**Comment by kinnison** [comment] 2019-09-25 08:12
My apologies, it looks like the artifacts don't get collected, so you'll need to build a copy locally.

**Comment by Vlad-Shcherbina** [comment] 2019-09-25 11:01
In the scenario I described, #2014 appears to work as expected.

**Closed** 2019-09-25 12:17 UTC
Labels: bug
